server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: bi
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


# HS512알고리즘, 64byte 이상 secret key 사용
# echo -n 'my-name-is-byeongil-hello-jwt-hahaha-my-name-is-byeongil-hello-jwt-hahaha' | openssl base64
jwt:
  header: Authorization
  secret: bXktbmFtZS1pcy1ieWVvbmdpbC1oZWxsby1qd3QtaGFoYWhhLW15LW5hbWUtaXMtYnllb25naWwtaGVsbG8tand0LWhhaGFoYQ==

logging:
  level:
    me.bi : DEBUG